import { createAsyncThunk, createSlice } from '@reduxjs/toolkit'
import { createAction } from '@reduxjs/toolkit'
import { Elements, FlowExportObject, isEdge } from 'react-flow-renderer'
import firebase from 'firebase/compat/app'
import { clean } from '../utils/clean'

export interface ChartState {
  elements: Elements,
  flowSideOpen: boolean

}

const initialState: ChartState = {
    elements: [],
    flowSideOpen: true
}

export const setElements = createAction<Elements>('flowChart/setElements')


export const saveFlowSetting = createAsyncThunk('flowChart/saveFlow', async ({flowId, name, tagLine, color, file}: {flowId: string, name: string, tagLine?: string, color: string, file: File | undefined}) => {
  if(file) {

    try {
      const fileExtension = file.path.split('.').pop()
      await firebase.storage().ref(`images/${flowId}.${fileExtension}`).put(file)
      await firebase.firestore().collection('flows').doc(flowId).set({
        logoName: `${flowId}.${fileExtension}`
        },
        { merge: true }
      )
    }catch(e) {
      console.error("iron dragon", e)
    }

  }

  try{
    await firebase.firestore().collection('flows').doc(flowId).set(clean({
      name,
      tagLine,
      color
    }), { merge: true })
  } catch(e){
    console.error("iron dragon", e)

  }

 
  return;
})

export const deleteFlowLogo = createAsyncThunk('flowChart/deleteFlowLogo', async ({flowId, logoName}: {flowId: string, logoName: string}) => {
  await firebase.firestore().collection('flows').doc(flowId).update({
    logoName: firebase.firestore.FieldValue.delete()
  })

  await firebase.storage().ref(`image/${logoName}`).delete()

})

export const saveFlow = createAsyncThunk('flowChart/saveFlow', async ({flowId, flowNodes}: {flowId: string, flowNodes: FlowExportObject<any>}) => {
    try {
      flowNodes.elements.forEach(element => {
        if(isEdge(element)) {
          delete element.data.onDeleteClicked
        }
      })
      await firebase.firestore().collection('flows').doc(flowId).set(flowNodes, { merge: true })
    }catch(e) {
      console.error("saving fail", e)
    }
    return;
})

export const deployFlow = createAsyncThunk('flowChart/deployFlow', async ({flowId, flowNodes}: {flowId: string, flowNodes: FlowExportObject<any>}, thunkAPI) => {
  await thunkAPI.dispatch(saveFlow({flowId, flowNodes}))

  try{
    const createProdFlow = firebase.functions().httpsCallable('createProdFlow');
    createProdFlow({flowId})
  }catch(e) {
    console.error(e)
  }

  return;
})

export const rollbackFlow = createAsyncThunk('flowChart/rollbackFlow', async ({releaseId, flowId}: { releaseId: string, flowId: string }, thunkAPI) => {

  try{
    const rollbackProdFlow = firebase.functions().httpsCallable('rollbackProdFlow');
    rollbackProdFlow({releaseId, flowId})
  }catch(e) {
    console.error(e)
  }

  return;
})

export const saveFlowForm = createAsyncThunk('flowChart/saveFlowForm', async ({flowId, flowFormId, flowForm}: {flowId:string, flowFormId: string, flowForm: any}) => {
    await firebase.firestore().collection('flowForms').doc(flowId).collection("forms").doc(flowFormId).set(clean(flowForm), { merge: true })
    return;
})

export const createNewFlow =  createAsyncThunk('flowChart/createFlow', async ({orgId}: {orgId: string}) => {
  const flowResp = await firebase.firestore().collection('flows').add({
    name: "New Flow"
  })
  await firebase.firestore().collection('organization').doc(orgId).update({
    flows: firebase.firestore.FieldValue.arrayUnion(flowResp.id)
  })

})

export const duplicateFlow = createAsyncThunk('flowChart/duplicateFlow', async ({flowId, organizationId}: {flowId: string, organizationId: string }, _thunkAPI) => {
  await fetch(`https://us-central1-onboard-os.cloudfunctions.net/duplicateFlow?flowId=${flowId}&organizationId=${organizationId}`, {
    method: "GET"
  })
})

export const flowChartSlice = createSlice({
  name: 'flowChart',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    toggleSidebar: (state) => {
      return {
        ...state,
        flowSideOpen: !state.flowSideOpen
      }
    },
    openSidebar: (state) => {
      return {
        ...state,
        flowSideOpen: true
      }
    }

  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder.addCase(setElements, (state, action) => {
      state.elements = action.payload
    })
    builder.addCase(saveFlow.pending, (state, action) => {

    })
  },
})

export const { toggleSidebar, openSidebar } = flowChartSlice.actions

export default flowChartSlice.reducer