import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit'
import { createAction, createReducer } from '@reduxjs/toolkit'
import { Elements } from 'react-flow-renderer'

import type { AppState, AppThunk } from '../app/store'

export interface ChartState {
  elements: Elements,
}

const initialState: ChartState = {
    elements: []
}

export const setElements = createAction<Elements>('flowChart/setElements')


export const flowChartSlice = createSlice({
  name: 'flowChart',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder.addCase(setElements, (state, action) => {
      state.elements = action.payload
    })
  },
})


export default flowChartSlice.reducer