import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit'
import { createAction, createReducer } from '@reduxjs/toolkit'

import type { AppState, AppThunk } from '../app/store'

export interface UIState {
  tab: 'screens' | 'preview',
  previewing?: string
}

const initialState: UIState = {
  tab: 'screens',
}

export const showPreviewOfNode = createAction<string>('ui/showPreview')


export const uiSlice = createSlice({
  name: 'ui',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    screenClick: (state) => {
      state.tab  = 'screens'
    },
    previewClick: (state) => {
        state.tab  = 'preview'
    },
    
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder.addCase(showPreviewOfNode, (state, action) => {
      console.log('showPreviewOfNode', action.payload)
      state.tab  = 'preview',
      state.previewing = action.payload
    })
  },
})

export const { screenClick, previewClick } = uiSlice.actions

export default uiSlice.reducer