import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit'
import { createAction, createReducer } from '@reduxjs/toolkit'

import type { AppState, AppThunk } from '../app/store'

export interface UIState {
  tab: 'screens' | 'preview' | 'design',
  screen: 'chart' | 'preview' | 'releases',
  previewing?: string
  isPreviewTest: boolean
}

const initialState: UIState = {
  tab: 'screens',
  screen: "chart",
  isPreviewTest: false
}

export const showPreviewOfNode = createAction<string>('ui/showPreview')


export const uiSlice = createSlice({
  name: 'ui',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    screenClick: (state) => {
      state.tab  = 'screens'
    },
    previewClick: (state) => {
        state.tab  = 'preview'
    },
    designClick: (state) => {
      state.tab  = 'design'
    },
    screenChartClicked: (state) => {
      state.screen = "chart"
    },
    screenPreviewClicked: (state) => {
      state.screen = "preview"
    },
    screenReleasesClicked: (state) => {
      state.screen = "releases"
    },
    togglePreviewTesting: (state) => {
      state.isPreviewTest = !state.isPreviewTest 
    }
    
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder.addCase(showPreviewOfNode, (state, action) => {
      state.tab  = 'preview',
      state.previewing = action.payload
    })
  },
})

export const { screenClick, previewClick, screenPreviewClicked, screenChartClicked, screenReleasesClicked, togglePreviewTesting, designClick } = uiSlice.actions

export default uiSlice.reducer