import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit'
import { createAction, createReducer } from '@reduxjs/toolkit'

import type { AppState, AppThunk } from '../app/store'

export interface UIState {
  tab: 'screens' | 'preview'
}

const initialState: UIState = {
  tab: 'screens',
}

export const uiSlice = createSlice({
  name: 'counter',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    screenClick: (state) => {
      state.tab  = 'screens'
    },
    previewClick: (state) => {
        state.tab  = 'preview'
    },
    
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    
  },
})

export const { screenClick, previewClick } = uiSlice.actions

export default uiSlice.reducer